name: Build and Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install Python dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Install C++ dependencies
        run: |
          sudo apt update
          sudo apt install cmake qt6-base-dev

      - name: Compile C++
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build --parallel

      - name: Prepare GTFS data
        run: |
          python3 scripts/convert.py

      - name: Run tests
        run: |
          ctest --test-dir build -V --output-on-failure
